configs:
  secret: 
    argocdServerAdminPassword: ""
  params: 
    server.insecure: true
fullnameOverride: "argocd"

server:
  ingress:
    enabled: true
    annotations:
      "helm.sh/hook": post-install
    ingressClassName: "nginx"
    hosts:
      - "argocd-ui"
# meta:
#   helm.sh/release-namespace: "argo-cd"